### ISSUE TITLE
Hello, I encounter some problems when I use your code. .ERROR: 05/06/2024 07:51:52 PM - utils.py - line 87 : 。It seems that there is a problem with the connection. Is it because it's trying to download the dataset by accessing a certain website? I look forward to your reply. Thank you.Traceback (most recent call last):   File "/home/lenovo/anaconda3/envs/JX/lib/python3.9/site-packages/urllib3/connection.py", line 198, in _new_conn     sock = connection.create_connection(   File "/home/lenovo/anaconda3/envs/JX/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection     raise err   File "/home/lenovo/anaconda3/envs/JX/lib/python3.9/site-packages/urllib3/util/connection.py", line 73, in create_connection     sock.connect(sa) OSError: [Errno 101] Network is unreachable。

### ISSUE THREAD

**Issue by depcco** [divelab/GOOD#30]
<img width="731" alt="1714996638780" src="https://github.com/divelab/GOOD/assets/169051868/5d915719-bd25-4b41-a199-8a03fa464984">

**Comment by CM-BF** [comment]
Hi @depcco,

Yes, datasets are stored on [Google Drive](https://github.com/divelab/GOOD/blob/fff0e2dc311e1d0e0a23052f6c601db4f185e12e/GOOD/data/good_datasets/good_motif.py#L44).

Best
